export const POST_FETCH = 'POST_FETCH';
export const POST_FETCH_CANCEL = 'POST_FETCH_CANCEL';
export const POST_FETCH_FAILED = 'POST_FETCH_FAILED';
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS';
